### PR TITLE
Convert the README into Markdown

### PR DESCRIPTION
**Pull request by mortenpi**
@cffischer here is a pull request to update the README. I've turned it into Markdown so that it would look nice and we could have badges, links etc.  The contents is the same, other than that I move the MIT license text into a separate file, so that [GitHub could pick up which license the repository uses](https://github.blog/2016-09-21-license-now-displayed-on-repository-overview/).

You can see the version I propose here: https://github.com/compas/grasp2018/tree/mp/readme

If it looks good to you, then I suggest we go ahead and merge it into the `master` branch.

### CODE REVIEW

**Comment by jongrumer** [comment]
Looks good @mortenpi! I'll go through it and add minor corrections if I find any, and if no one else complains by the end of the day, I'll merge it into master.

For the senior CompAS devs [ @cffischer @tspejo @gaigalas @bieronjacek @mrgodef ] and the rest of the group - note how this update is an example of a typical development workflow. Please take **5 minutes** to read through my explanation below:

1. **Idea**: @mortenpi wakes up one morning with the idea of improving the readme, license and so on, to make our repository feel more professional.
2. **Create a branch**: In order to do this, he creates a **branch** called `mp/readme` - the naming convention of branches is your name (in this case `mp` for Morten P) followed by a `/` and a descriptive name (in this case just `readme`). 
3. **Commits**: He switches over to his new branch  and starts working (which then doesn't touch the master or any other branch at all - so it is safe), in small incremental steps, and recording his changes by making **commits** to the branch (locally on his computer). This process of adding commits keeps track of your progress but also create a transparent history of your work that others can follow to understand what you've done and why. Each commit comes with a description of the modification you've done. In this particular case, Morten made 5 commits in total which you can se on top of this page if you're reading this on github  [github.com/compas/grasp2018/pull/7](https://github.com/compas/grasp2018/pull/7) - which you should be.
4. **Open a pull request**: When you're done (or stuck!) you open a **pull request** to initiate a discussion about your idea and the commits you've made. This is what Morten just did, he opened a pull request and initiated a discussion about his suggested changes. And also asking the manager(s) to approve a **merge** into the master branch. The rest of us can now contribute through discussions, and by improving Mortens branch with further commits if necessary - this typically happens. I will illustrate this by making some smaller modifications to his branch after I've finished this message.
5. **Merge**: Once the changes have been verified, it is time to merge the code into the master branch. Once merged, the pull requests preserve a record of the historical changes to your code. Because they're searchable, they let anyone go back in time to understand why and how a decision was made. This merge is typically done by some manager, which for the time being is me. Note that the manager should discuss and ask for advice about the pull request in question before approving.

That's all!

Note that you can create branches and commit changes etc on your local computer to which you have **cloned** the repository, or here directly on github by simply editing the files in the online editor. The latter method can be convenient for smaller modifications. I typically create branches and that type of admin on github, and then synchronise the (pull) the repository with my local version where the work then starts.

Hope this was a bit helpful - I fully realise that getting comfy with this workflow takes time - but please allocate some time to go through some tutorial at [guides.github.com](https://guides.github.com/) where there's also a nice hello world example which you can try out using your personal repository. Here you can learn all about how to synchronise your local copy of the repository with github.com/compas/grasp2018, how to create branches, pull requests and so on.

If you feel totally lost on all things git, I recommend you to watch the two first videos about version control with git at [git-scm.com/videos](https://git-scm.com/videos). Note that `git` and `github` are separate things: github is an online service based on git which is the actual version control program.

Cheers,
Jon

**Comment by jongrumer** [comment]
Note now that above this message after my previous one, there's an additional commit by me. **Click on it to learn more.** (again, please read all this on github and not in your email client: [github.com/compas/grasp2018/pull/7](https://github.com/compas/grasp2018/pull/7)).

This pull request now contains 6 commits in total: 5 by Morten and a minor one by me to illustrate the workflow.

To make sure you all have a chance to follow this unintended tutorial I will postpone the actual merge (step 5 above) until say tomorrow evening (Swedish time).

**Comment by mortenpi** [comment]
Your fixes look good to me @jongrumer!

**Comment by gaigalas** [comment]
I have a question.
Am I included in the compass/grasp2018 e-mail group?
I see that this e-mail was sent to compass/grasp2018 e-mail group and I have received it as cc.
Does it mean that my input into the GRASP isn’t sufficient to be included in the compass/grasp2018 e-mail group?

Best wishes,
Gediminas Gaigalas

**Comment by mortenpi** [comment]
@gaigalas: there is no email group as such. The email you received was a notification about this discussion thread. You can see that your email reply was added to the public thread here: https://github.com/compas/grasp2018/pull/7#issuecomment-467571055

You were notified because @jongrumer at-mentioned you. If you "watch" the repository, by clicking the "Watch" button at the top, you can get notifications about all the threads that are created.

* More about watching repositories: https://help.github.com/en/articles/watching-and-unwatching-repositories#watching-a-single-repository
* More about at-mentions: https://help.github.com/en/articles/basic-writing-and-formatting-syntax#mentioning-people-and-teams

**Comment by jongrumer** [comment]
So, since there have been no further objections or comments, I'll merge this branch into master now.

To reduce to amount of clutter in the master branch, we're gonna do a so called squash-merge, where all commits in this branch will be combined into a single commit in the master branch.

**Comment by mrgodef** [comment]
Jon,
It is a pity that you are acting so “quickly”.  I would like to follow this but I don’t think you can imagine what teaching means at ULB. In any case, will I be able to follow what you have done and how, once it will be done?
Michel
PS I wanted to do this with Sacha who will be back from a holidays, or with Kai who is currently back in China...
------------------------


Le 1 mars 2019 à 16:16, Jon Grumer <notifications@github.com<mailto:notifications@github.com>> a écrit :


So, since there have been no further objections or comments, I'll merge this branch into master now.

To reduce to amount of clutter in the master branch, we're gonna do a so called squash-merge, where all commits in this branch will be combined into a single commit in the master branch.

**Comment by jongrumer** [comment]
Hi @mrgodef - nice to hear from you!

Ok, sorry, I fully understand your situation - I got very few responses so I assumed no one was interested beyond me, @cffischer and @mortenpi , and I wanted to move on. I'm of course very happy to hear that wasn't the case! :) The fact that I performed the "merge" now doesn't affect the tutorial too much, you can still go into the Pull Request (here: https://github.com/compas/grasp2018/pull/7) that Morten initiated and go through the process. And feel free to ask questions and discuss there, using the message interface instead of with an email as you did now. The only thing is that you can't add any modifications yourself this time, but that doesn't affect my main purpose of this tutorial which more was to provide you with a complete workflow example.

We will for sure do more of these tutorials within the near future as well - don't worry! ;)
And I will take it slower that time.

Now it's beer a clock it seems! Have a good weekend!
Jon

**Pull request merged**
